name: code_bisync_flutter
description: A GUI tool for bidirectional local↔remote synchronization
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  file_selector: ^1.0.0
  path: ^1.8.0
  dartssh2: ^2.8.2
  rxdart: ^0.27.7
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
